---
apiVersion: v1
kind: Namespace
metadata:
  name: tracing-tutorial

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: tracing-tutorial
spec:
  selector:
    app: jaeger
  ports:
    - protocol: TCP
      port: 9411
      name: collector
      targetPort: 9411
    - protocol: TCP
      port: 16686
      name: web
      targetPort: 16686
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: tracing-tutorial
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one
          imagePullPolicy: Always
          ports:
            - containerPort: 9411
            - containerPort: 16686
