apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: goroutines
  namespace: goroutines
  labels:
    app: goroutines
spec:
  selector:
    matchLabels:
      app: goroutines
  endpoints:
  - port: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
    name: prometheus
    namespace: goroutines
spec:
    serviceMonitorSelector:
        matchLabels:
            app: goroutines
    resources:
        requests:
            memory: 400Mi
    enableAdminAPI: false
---
apiVersion: v1
kind: Service
metadata:
    name: prometheus
    namespace: goroutines
spec:
    type: NodePort
    ports:
    - name: web
      nodePort: 30900
      port: 9090
      protocol: TCP
      targetPort: web
    selector:
        prometheus: prometheus